### ISSUE TITLE
There is not license

### ISSUE THREAD

**Issue by pemCristina** [SomeKittens/Sudoku-Project#1]
Hi Randall,

Currently I am developing a Sudoku game in java and I would like to use your code to generate a random Sudoku, however there is not license. Could you update it?

Thank you for your attention to this matter.

**Comment by SomeKittens** [comment]
You're welcome to use whatever code you want from this project - though I'd recommend looking elsewhere, I never was very good at Java.

**Comment by pemCristina** [comment]
I've tested  the code and it works fine for me.
Thank you so much for your help!
